// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xstream_pack.proto

package com.aliyun.odps.commons.proto;

import com.google.protobuf.AbstractMessage;

public final class XstreamPack {
  private XstreamPack() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface XStreamPackOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes pack_data = 1;
    boolean hasPackData();
    com.google.protobuf.ByteString getPackData();
    
    // optional bytes pack_meta = 2;
    boolean hasPackMeta();
    com.google.protobuf.ByteString getPackMeta();
  }
  public static final class XStreamPack extends
      com.google.protobuf.GeneratedMessage
      implements XStreamPackOrBuilder {
    // Use XStreamPack.newBuilder() to construct.
    private XStreamPack(Builder builder) {
      super(builder);
    }
    private XStreamPack(boolean noInit) {}
    
    private static final XStreamPack defaultInstance;
    public static XStreamPack getDefaultInstance() {
      return defaultInstance;
    }
    
    public XStreamPack getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return XstreamPack.internal_static_com_aliyun_odps_tunnel_io_proto_XStreamPack_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return XstreamPack.internal_static_com_aliyun_odps_tunnel_io_proto_XStreamPack_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes pack_data = 1;
    public static final int PACK_DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString packData_;
    public boolean hasPackData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getPackData() {
      return packData_;
    }
    
    // optional bytes pack_meta = 2;
    public static final int PACK_META_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString packMeta_;
    public boolean hasPackMeta() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getPackMeta() {
      return packMeta_;
    }
    
    private void initFields() {
      packData_ = com.google.protobuf.ByteString.EMPTY;
      packMeta_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPackData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, packData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, packMeta_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, packData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, packMeta_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static XstreamPack.XStreamPack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static XstreamPack.XStreamPack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static XstreamPack.XStreamPack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static XstreamPack.XStreamPack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static XstreamPack.XStreamPack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static XstreamPack.XStreamPack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static XstreamPack.XStreamPack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static XstreamPack.XStreamPack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static XstreamPack.XStreamPack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static XstreamPack.XStreamPack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(XstreamPack.XStreamPack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements XstreamPack.XStreamPackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return XstreamPack.internal_static_com_aliyun_odps_tunnel_io_proto_XStreamPack_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return XstreamPack.internal_static_com_aliyun_odps_tunnel_io_proto_XStreamPack_fieldAccessorTable;
      }
      
      // Construct using com.aliyun.odps.commons.proto.XstreamPack.XStreamPack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        packData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        packMeta_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return XstreamPack.XStreamPack.getDescriptor();
      }
      
      public XstreamPack.XStreamPack getDefaultInstanceForType() {
        return XstreamPack.XStreamPack.getDefaultInstance();
      }
      
      public XstreamPack.XStreamPack build() {
        XstreamPack.XStreamPack result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }
      
      private XstreamPack.XStreamPack buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        XstreamPack.XStreamPack result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(
                  result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public XstreamPack.XStreamPack buildPartial() {
        XstreamPack.XStreamPack result = new XstreamPack.XStreamPack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packData_ = packData_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.packMeta_ = packMeta_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof XstreamPack.XStreamPack) {
          return mergeFrom((XstreamPack.XStreamPack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(XstreamPack.XStreamPack other) {
        if (other == XstreamPack.XStreamPack.getDefaultInstance()) return this;
        if (other.hasPackData()) {
          setPackData(other.getPackData());
        }
        if (other.hasPackMeta()) {
          setPackMeta(other.getPackMeta());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPackData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              packData_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              packMeta_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes pack_data = 1;
      private com.google.protobuf.ByteString packData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPackData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getPackData() {
        return packData_;
      }
      public Builder setPackData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packData_ = value;
        onChanged();
        return this;
      }
      public Builder clearPackData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packData_ = getDefaultInstance().getPackData();
        onChanged();
        return this;
      }
      
      // optional bytes pack_meta = 2;
      private com.google.protobuf.ByteString packMeta_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPackMeta() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getPackMeta() {
        return packMeta_;
      }
      public Builder setPackMeta(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        packMeta_ = value;
        onChanged();
        return this;
      }
      public Builder clearPackMeta() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packMeta_ = getDefaultInstance().getPackMeta();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.aliyun.odps.commons.proto.XStreamPack)
    }
    
    static {
      defaultInstance = new XStreamPack(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.aliyun.odps.commons.proto.XStreamPack)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aliyun_odps_tunnel_io_proto_XStreamPack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_aliyun_odps_tunnel_io_proto_XStreamPack_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022xstream_pack.proto\022\037com.aliyun.odps.tu" +
      "nnel.io.proto\"3\n\013XStreamPack\022\021\n\tpack_dat" +
      "a\030\001 \002(\014\022\021\n\tpack_meta\030\002 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_aliyun_odps_tunnel_io_proto_XStreamPack_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_aliyun_odps_tunnel_io_proto_XStreamPack_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_aliyun_odps_tunnel_io_proto_XStreamPack_descriptor,
              new java.lang.String[] { "PackData", "PackMeta", },
              XstreamPack.XStreamPack.class,
              XstreamPack.XStreamPack.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
