// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lot/aggregate.proto

package apsara.odps.lot;

public final class AggregateProtos {
  private AggregateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AggregateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string Id = 1;
    boolean hasId();
    String getId();
    
    // required string ParentId = 2;
    boolean hasParentId();
    String getParentId();
    
    // repeated .apsara.odps.Reference GroupByColumns = 3;
    java.util.List<apsara.odps.ExpressionProtos.Reference> 
        getGroupByColumnsList();
    apsara.odps.ExpressionProtos.Reference getGroupByColumns(int index);
    int getGroupByColumnsCount();
    java.util.List<? extends apsara.odps.ExpressionProtos.ReferenceOrBuilder> 
        getGroupByColumnsOrBuilderList();
    apsara.odps.ExpressionProtos.ReferenceOrBuilder getGroupByColumnsOrBuilder(
        int index);
    
    // repeated group Functions = 4 {
    java.util.List<Aggregate.Functions>
        getFunctionsList();
    Aggregate.Functions getFunctions(int index);
    int getFunctionsCount();
    java.util.List<? extends Aggregate.FunctionsOrBuilder>
        getFunctionsOrBuilderList();
    Aggregate.FunctionsOrBuilder getFunctionsOrBuilder(
        int index);
  }
  public static final class Aggregate extends
      com.google.protobuf.GeneratedMessage
      implements AggregateOrBuilder {
    // Use Aggregate.newBuilder() to construct.
    private Aggregate(Builder builder) {
      super(builder);
    }
    private Aggregate(boolean noInit) {}
    
    private static final Aggregate defaultInstance;
    public static Aggregate getDefaultInstance() {
      return defaultInstance;
    }
    
    public Aggregate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AggregateProtos.internal_static_apsara_odps_lot_Aggregate_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AggregateProtos.internal_static_apsara_odps_lot_Aggregate_fieldAccessorTable;
    }
    
    public interface FunctionsOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required .apsara.odps.lot.AggregationFunction Function = 1;
      boolean hasFunction();
      ExpressionProtos.AggregationFunction getFunction();
      ExpressionProtos.AggregationFunctionOrBuilder getFunctionOrBuilder();
      
      // required string Alias = 2;
      boolean hasAlias();
      String getAlias();
    }
    public static final class Functions extends
        com.google.protobuf.GeneratedMessage
        implements FunctionsOrBuilder {
      // Use Functions.newBuilder() to construct.
      private Functions(Builder builder) {
        super(builder);
      }
      private Functions(boolean noInit) {}
      
      private static final Functions defaultInstance;
      public static Functions getDefaultInstance() {
        return defaultInstance;
      }
      
      public Functions getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AggregateProtos.internal_static_apsara_odps_lot_Aggregate_Functions_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AggregateProtos.internal_static_apsara_odps_lot_Aggregate_Functions_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required .apsara.odps.lot.AggregationFunction Function = 1;
      public static final int FUNCTION_FIELD_NUMBER = 1;
      private ExpressionProtos.AggregationFunction function_;
      public boolean hasFunction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ExpressionProtos.AggregationFunction getFunction() {
        return function_;
      }
      public ExpressionProtos.AggregationFunctionOrBuilder getFunctionOrBuilder() {
        return function_;
      }
      
      // required string Alias = 2;
      public static final int ALIAS_FIELD_NUMBER = 2;
      private Object alias_;
      public boolean hasAlias() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAlias() {
        Object ref = alias_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            alias_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getAliasBytes() {
        Object ref = alias_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          alias_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        function_ = ExpressionProtos.AggregationFunction.getDefaultInstance();
        alias_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasFunction()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAlias()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getFunction().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(1, function_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getAliasBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, function_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getAliasBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static Functions parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static Functions parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static Functions parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static Functions parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static Functions parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static Functions parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static Functions parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static Functions parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static Functions parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static Functions parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Functions prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements FunctionsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return AggregateProtos.internal_static_apsara_odps_lot_Aggregate_Functions_descriptor;
        }
        
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return AggregateProtos.internal_static_apsara_odps_lot_Aggregate_Functions_fieldAccessorTable;
        }
        
        // Construct using apsara.odps.lot.AggregateProtos.Aggregate.Functions.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getFunctionFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          if (functionBuilder_ == null) {
            function_ = ExpressionProtos.AggregationFunction.getDefaultInstance();
          } else {
            functionBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          alias_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Functions.getDescriptor();
        }
        
        public Functions getDefaultInstanceForType() {
          return Functions.getDefaultInstance();
        }
        
        public Functions build() {
          Functions result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private Functions buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          Functions result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public Functions buildPartial() {
          Functions result = new Functions(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (functionBuilder_ == null) {
            result.function_ = function_;
          } else {
            result.function_ = functionBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.alias_ = alias_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Functions) {
            return mergeFrom((Functions)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(Functions other) {
          if (other == Functions.getDefaultInstance()) return this;
          if (other.hasFunction()) {
            mergeFunction(other.getFunction());
          }
          if (other.hasAlias()) {
            setAlias(other.getAlias());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasFunction()) {
            
            return false;
          }
          if (!hasAlias()) {
            
            return false;
          }
          if (!getFunction().isInitialized()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                ExpressionProtos.AggregationFunction.Builder subBuilder = ExpressionProtos.AggregationFunction.newBuilder();
                if (hasFunction()) {
                  subBuilder.mergeFrom(getFunction());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setFunction(subBuilder.buildPartial());
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                alias_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required .apsara.odps.lot.AggregationFunction Function = 1;
        private ExpressionProtos.AggregationFunction function_ = ExpressionProtos.AggregationFunction.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            ExpressionProtos.AggregationFunction, ExpressionProtos.AggregationFunction.Builder, ExpressionProtos.AggregationFunctionOrBuilder> functionBuilder_;
        public boolean hasFunction() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public ExpressionProtos.AggregationFunction getFunction() {
          if (functionBuilder_ == null) {
            return function_;
          } else {
            return functionBuilder_.getMessage();
          }
        }
        public Builder setFunction(ExpressionProtos.AggregationFunction value) {
          if (functionBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            function_ = value;
            onChanged();
          } else {
            functionBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder setFunction(
            ExpressionProtos.AggregationFunction.Builder builderForValue) {
          if (functionBuilder_ == null) {
            function_ = builderForValue.build();
            onChanged();
          } else {
            functionBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder mergeFunction(ExpressionProtos.AggregationFunction value) {
          if (functionBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                function_ != ExpressionProtos.AggregationFunction.getDefaultInstance()) {
              function_ =
                ExpressionProtos.AggregationFunction.newBuilder(function_).mergeFrom(value).buildPartial();
            } else {
              function_ = value;
            }
            onChanged();
          } else {
            functionBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder clearFunction() {
          if (functionBuilder_ == null) {
            function_ = ExpressionProtos.AggregationFunction.getDefaultInstance();
            onChanged();
          } else {
            functionBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        public ExpressionProtos.AggregationFunction.Builder getFunctionBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getFunctionFieldBuilder().getBuilder();
        }
        public ExpressionProtos.AggregationFunctionOrBuilder getFunctionOrBuilder() {
          if (functionBuilder_ != null) {
            return functionBuilder_.getMessageOrBuilder();
          } else {
            return function_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            ExpressionProtos.AggregationFunction, ExpressionProtos.AggregationFunction.Builder, ExpressionProtos.AggregationFunctionOrBuilder>
            getFunctionFieldBuilder() {
          if (functionBuilder_ == null) {
            functionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                ExpressionProtos.AggregationFunction, ExpressionProtos.AggregationFunction.Builder, ExpressionProtos.AggregationFunctionOrBuilder>(
                    function_,
                    getParentForChildren(),
                    isClean());
            function_ = null;
          }
          return functionBuilder_;
        }
        
        // required string Alias = 2;
        private Object alias_ = "";
        public boolean hasAlias() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getAlias() {
          Object ref = alias_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            alias_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setAlias(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          alias_ = value;
          onChanged();
          return this;
        }
        public Builder clearAlias() {
          bitField0_ = (bitField0_ & ~0x00000002);
          alias_ = getDefaultInstance().getAlias();
          onChanged();
          return this;
        }
        void setAlias(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          alias_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:apsara.odps.lot.Aggregate.Functions)
      }
      
      static {
        defaultInstance = new Functions(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:apsara.odps.lot.Aggregate.Functions)
    }
    
    private int bitField0_;
    // required string Id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string ParentId = 2;
    public static final int PARENTID_FIELD_NUMBER = 2;
    private Object parentId_;
    public boolean hasParentId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getParentId() {
      Object ref = parentId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          parentId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getParentIdBytes() {
      Object ref = parentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .apsara.odps.Reference GroupByColumns = 3;
    public static final int GROUPBYCOLUMNS_FIELD_NUMBER = 3;
    private java.util.List<apsara.odps.ExpressionProtos.Reference> groupByColumns_;
    public java.util.List<apsara.odps.ExpressionProtos.Reference> getGroupByColumnsList() {
      return groupByColumns_;
    }
    public java.util.List<? extends apsara.odps.ExpressionProtos.ReferenceOrBuilder> 
        getGroupByColumnsOrBuilderList() {
      return groupByColumns_;
    }
    public int getGroupByColumnsCount() {
      return groupByColumns_.size();
    }
    public apsara.odps.ExpressionProtos.Reference getGroupByColumns(int index) {
      return groupByColumns_.get(index);
    }
    public apsara.odps.ExpressionProtos.ReferenceOrBuilder getGroupByColumnsOrBuilder(
        int index) {
      return groupByColumns_.get(index);
    }
    
    // repeated group Functions = 4 {
    public static final int FUNCTIONS_FIELD_NUMBER = 4;
    private java.util.List<Functions> functions_;
    public java.util.List<Functions> getFunctionsList() {
      return functions_;
    }
    public java.util.List<? extends FunctionsOrBuilder>
        getFunctionsOrBuilderList() {
      return functions_;
    }
    public int getFunctionsCount() {
      return functions_.size();
    }
    public Functions getFunctions(int index) {
      return functions_.get(index);
    }
    public FunctionsOrBuilder getFunctionsOrBuilder(
        int index) {
      return functions_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      parentId_ = "";
      groupByColumns_ = java.util.Collections.emptyList();
      functions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getGroupByColumnsCount(); i++) {
        if (!getGroupByColumns(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getFunctionsCount(); i++) {
        if (!getFunctions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getParentIdBytes());
      }
      for (int i = 0; i < groupByColumns_.size(); i++) {
        output.writeMessage(3, groupByColumns_.get(i));
      }
      for (int i = 0; i < functions_.size(); i++) {
        output.writeGroup(4, functions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getParentIdBytes());
      }
      for (int i = 0; i < groupByColumns_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, groupByColumns_.get(i));
      }
      for (int i = 0; i < functions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeGroupSize(4, functions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Aggregate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Aggregate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Aggregate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Aggregate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Aggregate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Aggregate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Aggregate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Aggregate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Aggregate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Aggregate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Aggregate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements AggregateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AggregateProtos.internal_static_apsara_odps_lot_Aggregate_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AggregateProtos.internal_static_apsara_odps_lot_Aggregate_fieldAccessorTable;
      }
      
      // Construct using apsara.odps.lot.AggregateProtos.Aggregate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGroupByColumnsFieldBuilder();
          getFunctionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        parentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (groupByColumnsBuilder_ == null) {
          groupByColumns_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          groupByColumnsBuilder_.clear();
        }
        if (functionsBuilder_ == null) {
          functions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          functionsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Aggregate.getDescriptor();
      }
      
      public Aggregate getDefaultInstanceForType() {
        return Aggregate.getDefaultInstance();
      }
      
      public Aggregate build() {
        Aggregate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Aggregate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Aggregate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Aggregate buildPartial() {
        Aggregate result = new Aggregate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parentId_ = parentId_;
        if (groupByColumnsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            groupByColumns_ = java.util.Collections.unmodifiableList(groupByColumns_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.groupByColumns_ = groupByColumns_;
        } else {
          result.groupByColumns_ = groupByColumnsBuilder_.build();
        }
        if (functionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            functions_ = java.util.Collections.unmodifiableList(functions_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.functions_ = functions_;
        } else {
          result.functions_ = functionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Aggregate) {
          return mergeFrom((Aggregate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Aggregate other) {
        if (other == Aggregate.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasParentId()) {
          setParentId(other.getParentId());
        }
        if (groupByColumnsBuilder_ == null) {
          if (!other.groupByColumns_.isEmpty()) {
            if (groupByColumns_.isEmpty()) {
              groupByColumns_ = other.groupByColumns_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureGroupByColumnsIsMutable();
              groupByColumns_.addAll(other.groupByColumns_);
            }
            onChanged();
          }
        } else {
          if (!other.groupByColumns_.isEmpty()) {
            if (groupByColumnsBuilder_.isEmpty()) {
              groupByColumnsBuilder_.dispose();
              groupByColumnsBuilder_ = null;
              groupByColumns_ = other.groupByColumns_;
              bitField0_ = (bitField0_ & ~0x00000004);
              groupByColumnsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGroupByColumnsFieldBuilder() : null;
            } else {
              groupByColumnsBuilder_.addAllMessages(other.groupByColumns_);
            }
          }
        }
        if (functionsBuilder_ == null) {
          if (!other.functions_.isEmpty()) {
            if (functions_.isEmpty()) {
              functions_ = other.functions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureFunctionsIsMutable();
              functions_.addAll(other.functions_);
            }
            onChanged();
          }
        } else {
          if (!other.functions_.isEmpty()) {
            if (functionsBuilder_.isEmpty()) {
              functionsBuilder_.dispose();
              functionsBuilder_ = null;
              functions_ = other.functions_;
              bitField0_ = (bitField0_ & ~0x00000008);
              functionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFunctionsFieldBuilder() : null;
            } else {
              functionsBuilder_.addAllMessages(other.functions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasParentId()) {
          
          return false;
        }
        for (int i = 0; i < getGroupByColumnsCount(); i++) {
          if (!getGroupByColumns(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getFunctionsCount(); i++) {
          if (!getFunctions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              parentId_ = input.readBytes();
              break;
            }
            case 26: {
              apsara.odps.ExpressionProtos.Reference.Builder subBuilder = apsara.odps.ExpressionProtos.Reference.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGroupByColumns(subBuilder.buildPartial());
              break;
            }
            case 35: {
              Functions.Builder subBuilder = Functions.newBuilder();
              input.readGroup(4, subBuilder, extensionRegistry);
              addFunctions(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string Id = 1;
      private Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string ParentId = 2;
      private Object parentId_ = "";
      public boolean hasParentId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getParentId() {
        Object ref = parentId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          parentId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setParentId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parentId_ = value;
        onChanged();
        return this;
      }
      public Builder clearParentId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }
      void setParentId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        parentId_ = value;
        onChanged();
      }
      
      // repeated .apsara.odps.Reference GroupByColumns = 3;
      private java.util.List<apsara.odps.ExpressionProtos.Reference> groupByColumns_ =
        java.util.Collections.emptyList();
      private void ensureGroupByColumnsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          groupByColumns_ = new java.util.ArrayList<apsara.odps.ExpressionProtos.Reference>(groupByColumns_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          apsara.odps.ExpressionProtos.Reference, apsara.odps.ExpressionProtos.Reference.Builder, apsara.odps.ExpressionProtos.ReferenceOrBuilder> groupByColumnsBuilder_;
      
      public java.util.List<apsara.odps.ExpressionProtos.Reference> getGroupByColumnsList() {
        if (groupByColumnsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(groupByColumns_);
        } else {
          return groupByColumnsBuilder_.getMessageList();
        }
      }
      public int getGroupByColumnsCount() {
        if (groupByColumnsBuilder_ == null) {
          return groupByColumns_.size();
        } else {
          return groupByColumnsBuilder_.getCount();
        }
      }
      public apsara.odps.ExpressionProtos.Reference getGroupByColumns(int index) {
        if (groupByColumnsBuilder_ == null) {
          return groupByColumns_.get(index);
        } else {
          return groupByColumnsBuilder_.getMessage(index);
        }
      }
      public Builder setGroupByColumns(
          int index, apsara.odps.ExpressionProtos.Reference value) {
        if (groupByColumnsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupByColumnsIsMutable();
          groupByColumns_.set(index, value);
          onChanged();
        } else {
          groupByColumnsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGroupByColumns(
          int index, apsara.odps.ExpressionProtos.Reference.Builder builderForValue) {
        if (groupByColumnsBuilder_ == null) {
          ensureGroupByColumnsIsMutable();
          groupByColumns_.set(index, builderForValue.build());
          onChanged();
        } else {
          groupByColumnsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGroupByColumns(apsara.odps.ExpressionProtos.Reference value) {
        if (groupByColumnsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupByColumnsIsMutable();
          groupByColumns_.add(value);
          onChanged();
        } else {
          groupByColumnsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGroupByColumns(
          int index, apsara.odps.ExpressionProtos.Reference value) {
        if (groupByColumnsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupByColumnsIsMutable();
          groupByColumns_.add(index, value);
          onChanged();
        } else {
          groupByColumnsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGroupByColumns(
          apsara.odps.ExpressionProtos.Reference.Builder builderForValue) {
        if (groupByColumnsBuilder_ == null) {
          ensureGroupByColumnsIsMutable();
          groupByColumns_.add(builderForValue.build());
          onChanged();
        } else {
          groupByColumnsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGroupByColumns(
          int index, apsara.odps.ExpressionProtos.Reference.Builder builderForValue) {
        if (groupByColumnsBuilder_ == null) {
          ensureGroupByColumnsIsMutable();
          groupByColumns_.add(index, builderForValue.build());
          onChanged();
        } else {
          groupByColumnsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGroupByColumns(
          Iterable<? extends apsara.odps.ExpressionProtos.Reference> values) {
        if (groupByColumnsBuilder_ == null) {
          ensureGroupByColumnsIsMutable();
          super.addAll(values, groupByColumns_);
          onChanged();
        } else {
          groupByColumnsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGroupByColumns() {
        if (groupByColumnsBuilder_ == null) {
          groupByColumns_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          groupByColumnsBuilder_.clear();
        }
        return this;
      }
      public Builder removeGroupByColumns(int index) {
        if (groupByColumnsBuilder_ == null) {
          ensureGroupByColumnsIsMutable();
          groupByColumns_.remove(index);
          onChanged();
        } else {
          groupByColumnsBuilder_.remove(index);
        }
        return this;
      }
      public apsara.odps.ExpressionProtos.Reference.Builder getGroupByColumnsBuilder(
          int index) {
        return getGroupByColumnsFieldBuilder().getBuilder(index);
      }
      public apsara.odps.ExpressionProtos.ReferenceOrBuilder getGroupByColumnsOrBuilder(
          int index) {
        if (groupByColumnsBuilder_ == null) {
          return groupByColumns_.get(index);  } else {
          return groupByColumnsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends apsara.odps.ExpressionProtos.ReferenceOrBuilder> 
           getGroupByColumnsOrBuilderList() {
        if (groupByColumnsBuilder_ != null) {
          return groupByColumnsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(groupByColumns_);
        }
      }
      public apsara.odps.ExpressionProtos.Reference.Builder addGroupByColumnsBuilder() {
        return getGroupByColumnsFieldBuilder().addBuilder(
            apsara.odps.ExpressionProtos.Reference.getDefaultInstance());
      }
      public apsara.odps.ExpressionProtos.Reference.Builder addGroupByColumnsBuilder(
          int index) {
        return getGroupByColumnsFieldBuilder().addBuilder(
            index, apsara.odps.ExpressionProtos.Reference.getDefaultInstance());
      }
      public java.util.List<apsara.odps.ExpressionProtos.Reference.Builder> 
           getGroupByColumnsBuilderList() {
        return getGroupByColumnsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          apsara.odps.ExpressionProtos.Reference, apsara.odps.ExpressionProtos.Reference.Builder, apsara.odps.ExpressionProtos.ReferenceOrBuilder> 
          getGroupByColumnsFieldBuilder() {
        if (groupByColumnsBuilder_ == null) {
          groupByColumnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              apsara.odps.ExpressionProtos.Reference, apsara.odps.ExpressionProtos.Reference.Builder, apsara.odps.ExpressionProtos.ReferenceOrBuilder>(
                  groupByColumns_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          groupByColumns_ = null;
        }
        return groupByColumnsBuilder_;
      }
      
      // repeated group Functions = 4 {
      private java.util.List<Functions> functions_ =
        java.util.Collections.emptyList();
      private void ensureFunctionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          functions_ = new java.util.ArrayList<Functions>(functions_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          Functions, Functions.Builder, FunctionsOrBuilder> functionsBuilder_;
      
      public java.util.List<Functions> getFunctionsList() {
        if (functionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(functions_);
        } else {
          return functionsBuilder_.getMessageList();
        }
      }
      public int getFunctionsCount() {
        if (functionsBuilder_ == null) {
          return functions_.size();
        } else {
          return functionsBuilder_.getCount();
        }
      }
      public Functions getFunctions(int index) {
        if (functionsBuilder_ == null) {
          return functions_.get(index);
        } else {
          return functionsBuilder_.getMessage(index);
        }
      }
      public Builder setFunctions(
          int index, Functions value) {
        if (functionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFunctionsIsMutable();
          functions_.set(index, value);
          onChanged();
        } else {
          functionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFunctions(
          int index, Functions.Builder builderForValue) {
        if (functionsBuilder_ == null) {
          ensureFunctionsIsMutable();
          functions_.set(index, builderForValue.build());
          onChanged();
        } else {
          functionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFunctions(Functions value) {
        if (functionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFunctionsIsMutable();
          functions_.add(value);
          onChanged();
        } else {
          functionsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFunctions(
          int index, Functions value) {
        if (functionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFunctionsIsMutable();
          functions_.add(index, value);
          onChanged();
        } else {
          functionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFunctions(
          Functions.Builder builderForValue) {
        if (functionsBuilder_ == null) {
          ensureFunctionsIsMutable();
          functions_.add(builderForValue.build());
          onChanged();
        } else {
          functionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFunctions(
          int index, Functions.Builder builderForValue) {
        if (functionsBuilder_ == null) {
          ensureFunctionsIsMutable();
          functions_.add(index, builderForValue.build());
          onChanged();
        } else {
          functionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFunctions(
          Iterable<? extends Functions> values) {
        if (functionsBuilder_ == null) {
          ensureFunctionsIsMutable();
          super.addAll(values, functions_);
          onChanged();
        } else {
          functionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFunctions() {
        if (functionsBuilder_ == null) {
          functions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          functionsBuilder_.clear();
        }
        return this;
      }
      public Builder removeFunctions(int index) {
        if (functionsBuilder_ == null) {
          ensureFunctionsIsMutable();
          functions_.remove(index);
          onChanged();
        } else {
          functionsBuilder_.remove(index);
        }
        return this;
      }
      public Functions.Builder getFunctionsBuilder(
          int index) {
        return getFunctionsFieldBuilder().getBuilder(index);
      }
      public FunctionsOrBuilder getFunctionsOrBuilder(
          int index) {
        if (functionsBuilder_ == null) {
          return functions_.get(index);  } else {
          return functionsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends FunctionsOrBuilder>
           getFunctionsOrBuilderList() {
        if (functionsBuilder_ != null) {
          return functionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(functions_);
        }
      }
      public Functions.Builder addFunctionsBuilder() {
        return getFunctionsFieldBuilder().addBuilder(
            Functions.getDefaultInstance());
      }
      public Functions.Builder addFunctionsBuilder(
          int index) {
        return getFunctionsFieldBuilder().addBuilder(
            index, Functions.getDefaultInstance());
      }
      public java.util.List<Functions.Builder>
           getFunctionsBuilderList() {
        return getFunctionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Functions, Functions.Builder, FunctionsOrBuilder>
          getFunctionsFieldBuilder() {
        if (functionsBuilder_ == null) {
          functionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Functions, Functions.Builder, FunctionsOrBuilder>(
                  functions_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          functions_ = null;
        }
        return functionsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:apsara.odps.lot.Aggregate)
    }
    
    static {
      defaultInstance = new Aggregate(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:apsara.odps.lot.Aggregate)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_apsara_odps_lot_Aggregate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apsara_odps_lot_Aggregate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_apsara_odps_lot_Aggregate_Functions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apsara_odps_lot_Aggregate_Functions_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023lot/aggregate.proto\022\017apsara.odps.lot\032\027" +
      "common/expression.proto\032\024lot/expression." +
      "proto\"\346\001\n\tAggregate\022\n\n\002Id\030\001 \002(\t\022\020\n\010Paren" +
      "tId\030\002 \002(\t\022.\n\016GroupByColumns\030\003 \003(\0132\026.apsa" +
      "ra.odps.Reference\0227\n\tfunctions\030\004 \003(\n2$.a" +
      "psara.odps.lot.Aggregate.Functions\032R\n\tFu" +
      "nctions\0226\n\010Function\030\001 \002(\0132$.apsara.odps." +
      "lot.AggregationFunction\022\r\n\005Alias\030\002 \002(\tB\021" +
      "B\017AggregateProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_apsara_odps_lot_Aggregate_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_apsara_odps_lot_Aggregate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_apsara_odps_lot_Aggregate_descriptor,
              new String[] { "Id", "ParentId", "GroupByColumns", "Functions", },
              Aggregate.class,
              Aggregate.Builder.class);
          internal_static_apsara_odps_lot_Aggregate_Functions_descriptor =
            internal_static_apsara_odps_lot_Aggregate_descriptor.getNestedTypes().get(0);
          internal_static_apsara_odps_lot_Aggregate_Functions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_apsara_odps_lot_Aggregate_Functions_descriptor,
              new String[] { "Function", "Alias", },
              Aggregate.Functions.class,
              Aggregate.Functions.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          apsara.odps.ExpressionProtos.getDescriptor(),
          ExpressionProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
