// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lot/select.proto

package apsara.odps.lot;

public final class SelectProtos {
  private SelectProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SelectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string Id = 1;
    boolean hasId();
    String getId();
    
    // required string ParentId = 2;
    boolean hasParentId();
    String getParentId();
    
    // repeated group Expressions = 3 {
    java.util.List<Select.Expressions>
        getExpressionsList();
    Select.Expressions getExpressions(int index);
    int getExpressionsCount();
    java.util.List<? extends Select.ExpressionsOrBuilder>
        getExpressionsOrBuilderList();
    Select.ExpressionsOrBuilder getExpressionsOrBuilder(
        int index);
    
    // optional string TempTableName = 4;
    boolean hasTempTableName();
    String getTempTableName();
  }
  public static final class Select extends
      com.google.protobuf.GeneratedMessage
      implements SelectOrBuilder {
    // Use Select.newBuilder() to construct.
    private Select(Builder builder) {
      super(builder);
    }
    private Select(boolean noInit) {}
    
    private static final Select defaultInstance;
    public static Select getDefaultInstance() {
      return defaultInstance;
    }
    
    public Select getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SelectProtos.internal_static_apsara_odps_lot_Select_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SelectProtos.internal_static_apsara_odps_lot_Select_fieldAccessorTable;
    }
    
    public interface ExpressionsOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required .apsara.odps.lot.ScalarExpression Expression = 1;
      boolean hasExpression();
      ExpressionProtos.ScalarExpression getExpression();
      ExpressionProtos.ScalarExpressionOrBuilder getExpressionOrBuilder();
      
      // required string Alias = 2;
      boolean hasAlias();
      String getAlias();
    }
    public static final class Expressions extends
        com.google.protobuf.GeneratedMessage
        implements ExpressionsOrBuilder {
      // Use Expressions.newBuilder() to construct.
      private Expressions(Builder builder) {
        super(builder);
      }
      private Expressions(boolean noInit) {}
      
      private static final Expressions defaultInstance;
      public static Expressions getDefaultInstance() {
        return defaultInstance;
      }
      
      public Expressions getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SelectProtos.internal_static_apsara_odps_lot_Select_Expressions_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SelectProtos.internal_static_apsara_odps_lot_Select_Expressions_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required .apsara.odps.lot.ScalarExpression Expression = 1;
      public static final int EXPRESSION_FIELD_NUMBER = 1;
      private ExpressionProtos.ScalarExpression expression_;
      public boolean hasExpression() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ExpressionProtos.ScalarExpression getExpression() {
        return expression_;
      }
      public ExpressionProtos.ScalarExpressionOrBuilder getExpressionOrBuilder() {
        return expression_;
      }
      
      // required string Alias = 2;
      public static final int ALIAS_FIELD_NUMBER = 2;
      private Object alias_;
      public boolean hasAlias() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAlias() {
        Object ref = alias_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            alias_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getAliasBytes() {
        Object ref = alias_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          alias_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        expression_ = ExpressionProtos.ScalarExpression.getDefaultInstance();
        alias_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasExpression()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAlias()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getExpression().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(1, expression_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getAliasBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, expression_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getAliasBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static Expressions parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static Expressions parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static Expressions parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static Expressions parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static Expressions parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static Expressions parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static Expressions parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static Expressions parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static Expressions parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static Expressions parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Expressions prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ExpressionsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SelectProtos.internal_static_apsara_odps_lot_Select_Expressions_descriptor;
        }
        
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SelectProtos.internal_static_apsara_odps_lot_Select_Expressions_fieldAccessorTable;
        }
        
        // Construct using apsara.odps.lot.SelectProtos.Select.Expressions.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getExpressionFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          if (expressionBuilder_ == null) {
            expression_ = ExpressionProtos.ScalarExpression.getDefaultInstance();
          } else {
            expressionBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          alias_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Expressions.getDescriptor();
        }
        
        public Expressions getDefaultInstanceForType() {
          return Expressions.getDefaultInstance();
        }
        
        public Expressions build() {
          Expressions result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private Expressions buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          Expressions result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public Expressions buildPartial() {
          Expressions result = new Expressions(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (expressionBuilder_ == null) {
            result.expression_ = expression_;
          } else {
            result.expression_ = expressionBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.alias_ = alias_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Expressions) {
            return mergeFrom((Expressions)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(Expressions other) {
          if (other == Expressions.getDefaultInstance()) return this;
          if (other.hasExpression()) {
            mergeExpression(other.getExpression());
          }
          if (other.hasAlias()) {
            setAlias(other.getAlias());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasExpression()) {
            
            return false;
          }
          if (!hasAlias()) {
            
            return false;
          }
          if (!getExpression().isInitialized()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                ExpressionProtos.ScalarExpression.Builder subBuilder = ExpressionProtos.ScalarExpression.newBuilder();
                if (hasExpression()) {
                  subBuilder.mergeFrom(getExpression());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setExpression(subBuilder.buildPartial());
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                alias_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required .apsara.odps.lot.ScalarExpression Expression = 1;
        private ExpressionProtos.ScalarExpression expression_ = ExpressionProtos.ScalarExpression.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            ExpressionProtos.ScalarExpression, ExpressionProtos.ScalarExpression.Builder, ExpressionProtos.ScalarExpressionOrBuilder> expressionBuilder_;
        public boolean hasExpression() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public ExpressionProtos.ScalarExpression getExpression() {
          if (expressionBuilder_ == null) {
            return expression_;
          } else {
            return expressionBuilder_.getMessage();
          }
        }
        public Builder setExpression(ExpressionProtos.ScalarExpression value) {
          if (expressionBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            expression_ = value;
            onChanged();
          } else {
            expressionBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder setExpression(
            ExpressionProtos.ScalarExpression.Builder builderForValue) {
          if (expressionBuilder_ == null) {
            expression_ = builderForValue.build();
            onChanged();
          } else {
            expressionBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder mergeExpression(ExpressionProtos.ScalarExpression value) {
          if (expressionBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                expression_ != ExpressionProtos.ScalarExpression.getDefaultInstance()) {
              expression_ =
                ExpressionProtos.ScalarExpression.newBuilder(expression_).mergeFrom(value).buildPartial();
            } else {
              expression_ = value;
            }
            onChanged();
          } else {
            expressionBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder clearExpression() {
          if (expressionBuilder_ == null) {
            expression_ = ExpressionProtos.ScalarExpression.getDefaultInstance();
            onChanged();
          } else {
            expressionBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        public ExpressionProtos.ScalarExpression.Builder getExpressionBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getExpressionFieldBuilder().getBuilder();
        }
        public ExpressionProtos.ScalarExpressionOrBuilder getExpressionOrBuilder() {
          if (expressionBuilder_ != null) {
            return expressionBuilder_.getMessageOrBuilder();
          } else {
            return expression_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            ExpressionProtos.ScalarExpression, ExpressionProtos.ScalarExpression.Builder, ExpressionProtos.ScalarExpressionOrBuilder>
            getExpressionFieldBuilder() {
          if (expressionBuilder_ == null) {
            expressionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                ExpressionProtos.ScalarExpression, ExpressionProtos.ScalarExpression.Builder, ExpressionProtos.ScalarExpressionOrBuilder>(
                    expression_,
                    getParentForChildren(),
                    isClean());
            expression_ = null;
          }
          return expressionBuilder_;
        }
        
        // required string Alias = 2;
        private Object alias_ = "";
        public boolean hasAlias() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getAlias() {
          Object ref = alias_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            alias_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setAlias(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          alias_ = value;
          onChanged();
          return this;
        }
        public Builder clearAlias() {
          bitField0_ = (bitField0_ & ~0x00000002);
          alias_ = getDefaultInstance().getAlias();
          onChanged();
          return this;
        }
        void setAlias(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          alias_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:apsara.odps.lot.Select.Expressions)
      }
      
      static {
        defaultInstance = new Expressions(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:apsara.odps.lot.Select.Expressions)
    }
    
    private int bitField0_;
    // required string Id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string ParentId = 2;
    public static final int PARENTID_FIELD_NUMBER = 2;
    private Object parentId_;
    public boolean hasParentId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getParentId() {
      Object ref = parentId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          parentId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getParentIdBytes() {
      Object ref = parentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated group Expressions = 3 {
    public static final int EXPRESSIONS_FIELD_NUMBER = 3;
    private java.util.List<Expressions> expressions_;
    public java.util.List<Expressions> getExpressionsList() {
      return expressions_;
    }
    public java.util.List<? extends ExpressionsOrBuilder>
        getExpressionsOrBuilderList() {
      return expressions_;
    }
    public int getExpressionsCount() {
      return expressions_.size();
    }
    public Expressions getExpressions(int index) {
      return expressions_.get(index);
    }
    public ExpressionsOrBuilder getExpressionsOrBuilder(
        int index) {
      return expressions_.get(index);
    }
    
    // optional string TempTableName = 4;
    public static final int TEMPTABLENAME_FIELD_NUMBER = 4;
    private Object tempTableName_;
    public boolean hasTempTableName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTempTableName() {
      Object ref = tempTableName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tempTableName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTempTableNameBytes() {
      Object ref = tempTableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tempTableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      parentId_ = "";
      expressions_ = java.util.Collections.emptyList();
      tempTableName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getExpressionsCount(); i++) {
        if (!getExpressions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getParentIdBytes());
      }
      for (int i = 0; i < expressions_.size(); i++) {
        output.writeGroup(3, expressions_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getTempTableNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getParentIdBytes());
      }
      for (int i = 0; i < expressions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeGroupSize(3, expressions_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTempTableNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Select parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Select parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Select parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Select parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Select parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Select parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Select parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Select parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Select parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Select parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Select prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SelectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SelectProtos.internal_static_apsara_odps_lot_Select_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SelectProtos.internal_static_apsara_odps_lot_Select_fieldAccessorTable;
      }
      
      // Construct using apsara.odps.lot.SelectProtos.Select.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExpressionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        parentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (expressionsBuilder_ == null) {
          expressions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          expressionsBuilder_.clear();
        }
        tempTableName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Select.getDescriptor();
      }
      
      public Select getDefaultInstanceForType() {
        return Select.getDefaultInstance();
      }
      
      public Select build() {
        Select result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Select buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Select result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Select buildPartial() {
        Select result = new Select(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parentId_ = parentId_;
        if (expressionsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            expressions_ = java.util.Collections.unmodifiableList(expressions_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.expressions_ = expressions_;
        } else {
          result.expressions_ = expressionsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tempTableName_ = tempTableName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Select) {
          return mergeFrom((Select)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Select other) {
        if (other == Select.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasParentId()) {
          setParentId(other.getParentId());
        }
        if (expressionsBuilder_ == null) {
          if (!other.expressions_.isEmpty()) {
            if (expressions_.isEmpty()) {
              expressions_ = other.expressions_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureExpressionsIsMutable();
              expressions_.addAll(other.expressions_);
            }
            onChanged();
          }
        } else {
          if (!other.expressions_.isEmpty()) {
            if (expressionsBuilder_.isEmpty()) {
              expressionsBuilder_.dispose();
              expressionsBuilder_ = null;
              expressions_ = other.expressions_;
              bitField0_ = (bitField0_ & ~0x00000004);
              expressionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExpressionsFieldBuilder() : null;
            } else {
              expressionsBuilder_.addAllMessages(other.expressions_);
            }
          }
        }
        if (other.hasTempTableName()) {
          setTempTableName(other.getTempTableName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasParentId()) {
          
          return false;
        }
        for (int i = 0; i < getExpressionsCount(); i++) {
          if (!getExpressions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              parentId_ = input.readBytes();
              break;
            }
            case 27: {
              Expressions.Builder subBuilder = Expressions.newBuilder();
              input.readGroup(3, subBuilder, extensionRegistry);
              addExpressions(subBuilder.buildPartial());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              tempTableName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string Id = 1;
      private Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string ParentId = 2;
      private Object parentId_ = "";
      public boolean hasParentId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getParentId() {
        Object ref = parentId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          parentId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setParentId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parentId_ = value;
        onChanged();
        return this;
      }
      public Builder clearParentId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }
      void setParentId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        parentId_ = value;
        onChanged();
      }
      
      // repeated group Expressions = 3 {
      private java.util.List<Expressions> expressions_ =
        java.util.Collections.emptyList();
      private void ensureExpressionsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          expressions_ = new java.util.ArrayList<Expressions>(expressions_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          Expressions, Expressions.Builder, ExpressionsOrBuilder> expressionsBuilder_;
      
      public java.util.List<Expressions> getExpressionsList() {
        if (expressionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(expressions_);
        } else {
          return expressionsBuilder_.getMessageList();
        }
      }
      public int getExpressionsCount() {
        if (expressionsBuilder_ == null) {
          return expressions_.size();
        } else {
          return expressionsBuilder_.getCount();
        }
      }
      public Expressions getExpressions(int index) {
        if (expressionsBuilder_ == null) {
          return expressions_.get(index);
        } else {
          return expressionsBuilder_.getMessage(index);
        }
      }
      public Builder setExpressions(
          int index, Expressions value) {
        if (expressionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExpressionsIsMutable();
          expressions_.set(index, value);
          onChanged();
        } else {
          expressionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setExpressions(
          int index, Expressions.Builder builderForValue) {
        if (expressionsBuilder_ == null) {
          ensureExpressionsIsMutable();
          expressions_.set(index, builderForValue.build());
          onChanged();
        } else {
          expressionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addExpressions(Expressions value) {
        if (expressionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExpressionsIsMutable();
          expressions_.add(value);
          onChanged();
        } else {
          expressionsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addExpressions(
          int index, Expressions value) {
        if (expressionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExpressionsIsMutable();
          expressions_.add(index, value);
          onChanged();
        } else {
          expressionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addExpressions(
          Expressions.Builder builderForValue) {
        if (expressionsBuilder_ == null) {
          ensureExpressionsIsMutable();
          expressions_.add(builderForValue.build());
          onChanged();
        } else {
          expressionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addExpressions(
          int index, Expressions.Builder builderForValue) {
        if (expressionsBuilder_ == null) {
          ensureExpressionsIsMutable();
          expressions_.add(index, builderForValue.build());
          onChanged();
        } else {
          expressionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllExpressions(
          Iterable<? extends Expressions> values) {
        if (expressionsBuilder_ == null) {
          ensureExpressionsIsMutable();
          super.addAll(values, expressions_);
          onChanged();
        } else {
          expressionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearExpressions() {
        if (expressionsBuilder_ == null) {
          expressions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          expressionsBuilder_.clear();
        }
        return this;
      }
      public Builder removeExpressions(int index) {
        if (expressionsBuilder_ == null) {
          ensureExpressionsIsMutable();
          expressions_.remove(index);
          onChanged();
        } else {
          expressionsBuilder_.remove(index);
        }
        return this;
      }
      public Expressions.Builder getExpressionsBuilder(
          int index) {
        return getExpressionsFieldBuilder().getBuilder(index);
      }
      public ExpressionsOrBuilder getExpressionsOrBuilder(
          int index) {
        if (expressionsBuilder_ == null) {
          return expressions_.get(index);  } else {
          return expressionsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends ExpressionsOrBuilder>
           getExpressionsOrBuilderList() {
        if (expressionsBuilder_ != null) {
          return expressionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(expressions_);
        }
      }
      public Expressions.Builder addExpressionsBuilder() {
        return getExpressionsFieldBuilder().addBuilder(
            Expressions.getDefaultInstance());
      }
      public Expressions.Builder addExpressionsBuilder(
          int index) {
        return getExpressionsFieldBuilder().addBuilder(
            index, Expressions.getDefaultInstance());
      }
      public java.util.List<Expressions.Builder>
           getExpressionsBuilderList() {
        return getExpressionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Expressions, Expressions.Builder, ExpressionsOrBuilder>
          getExpressionsFieldBuilder() {
        if (expressionsBuilder_ == null) {
          expressionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Expressions, Expressions.Builder, ExpressionsOrBuilder>(
                  expressions_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          expressions_ = null;
        }
        return expressionsBuilder_;
      }
      
      // optional string TempTableName = 4;
      private Object tempTableName_ = "";
      public boolean hasTempTableName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getTempTableName() {
        Object ref = tempTableName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tempTableName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTempTableName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        tempTableName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTempTableName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tempTableName_ = getDefaultInstance().getTempTableName();
        onChanged();
        return this;
      }
      void setTempTableName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        tempTableName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:apsara.odps.lot.Select)
    }
    
    static {
      defaultInstance = new Select(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:apsara.odps.lot.Select)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_apsara_odps_lot_Select_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apsara_odps_lot_Select_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_apsara_odps_lot_Select_Expressions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apsara_odps_lot_Select_Expressions_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020lot/select.proto\022\017apsara.odps.lot\032\027com" +
      "mon/expression.proto\032\024lot/expression.pro" +
      "to\"\314\001\n\006Select\022\n\n\002Id\030\001 \002(\t\022\020\n\010ParentId\030\002 " +
      "\002(\t\0228\n\013expressions\030\003 \003(\n2#.apsara.odps.l" +
      "ot.Select.Expressions\022\025\n\rTempTableName\030\004" +
      " \001(\t\032S\n\013Expressions\0225\n\nExpression\030\001 \002(\0132" +
      "!.apsara.odps.lot.ScalarExpression\022\r\n\005Al" +
      "ias\030\002 \002(\tB\016B\014SelectProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_apsara_odps_lot_Select_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_apsara_odps_lot_Select_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_apsara_odps_lot_Select_descriptor,
              new String[] { "Id", "ParentId", "Expressions", "TempTableName", },
              Select.class,
              Select.Builder.class);
          internal_static_apsara_odps_lot_Select_Expressions_descriptor =
            internal_static_apsara_odps_lot_Select_descriptor.getNestedTypes().get(0);
          internal_static_apsara_odps_lot_Select_Expressions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_apsara_odps_lot_Select_Expressions_descriptor,
              new String[] { "Expression", "Alias", },
              Select.Expressions.class,
              Select.Expressions.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          apsara.odps.ExpressionProtos.getDescriptor(),
          ExpressionProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
