// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lot/tablescan.proto

package apsara.odps.lot;

import apsara.odps.PartitionSpecProtos;

public final class TableScanProtos {
  private TableScanProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TableScanOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string Project = 1;
    boolean hasProject();
    String getProject();
    
    // required string Table = 2;
    boolean hasTable();
    String getTable();
  }
  public static final class TableScan extends
      com.google.protobuf.GeneratedMessage
      implements TableScanOrBuilder {
    // Use TableScan.newBuilder() to construct.
    private TableScan(Builder builder) {
      super(builder);
    }
    private TableScan(boolean noInit) {}
    
    private static final TableScan defaultInstance;
    public static TableScan getDefaultInstance() {
      return defaultInstance;
    }
    
    public TableScan getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TableScanProtos.internal_static_apsara_odps_lot_TableScan_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TableScanProtos.internal_static_apsara_odps_lot_TableScan_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string Project = 1;
    public static final int PROJECT_FIELD_NUMBER = 1;
    private Object project_;
    public boolean hasProject() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getProject() {
      Object ref = project_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          project_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getProjectBytes() {
      Object ref = project_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        project_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Table = 2;
    public static final int TABLE_FIELD_NUMBER = 2;
    private Object table_;
    public boolean hasTable() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTable() {
      Object ref = table_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          table_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTableBytes() {
      Object ref = table_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        table_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      project_ = "";
      table_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasProject()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getProjectBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTableBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getProjectBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTableBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static TableScan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static TableScan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static TableScan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static TableScan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static TableScan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static TableScan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static TableScan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static TableScan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static TableScan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static TableScan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TableScan prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TableScanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TableScanProtos.internal_static_apsara_odps_lot_TableScan_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TableScanProtos.internal_static_apsara_odps_lot_TableScan_fieldAccessorTable;
      }
      
      // Construct using apsara.odps.lot.TableScanProtos.TableScan.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        project_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        table_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TableScan.getDescriptor();
      }
      
      public TableScan getDefaultInstanceForType() {
        return TableScan.getDefaultInstance();
      }
      
      public TableScan build() {
        TableScan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private TableScan buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        TableScan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public TableScan buildPartial() {
        TableScan result = new TableScan(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.project_ = project_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.table_ = table_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TableScan) {
          return mergeFrom((TableScan)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(TableScan other) {
        if (other == TableScan.getDefaultInstance()) return this;
        if (other.hasProject()) {
          setProject(other.getProject());
        }
        if (other.hasTable()) {
          setTable(other.getTable());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasProject()) {
          
          return false;
        }
        if (!hasTable()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              project_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              table_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string Project = 1;
      private Object project_ = "";
      public boolean hasProject() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getProject() {
        Object ref = project_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          project_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProject(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        project_ = value;
        onChanged();
        return this;
      }
      public Builder clearProject() {
        bitField0_ = (bitField0_ & ~0x00000001);
        project_ = getDefaultInstance().getProject();
        onChanged();
        return this;
      }
      void setProject(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        project_ = value;
        onChanged();
      }
      
      // required string Table = 2;
      private Object table_ = "";
      public boolean hasTable() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTable() {
        Object ref = table_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          table_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTable(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        table_ = value;
        onChanged();
        return this;
      }
      public Builder clearTable() {
        bitField0_ = (bitField0_ & ~0x00000002);
        table_ = getDefaultInstance().getTable();
        onChanged();
        return this;
      }
      void setTable(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        table_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:apsara.odps.lot.TableScan)
    }
    
    static {
      defaultInstance = new TableScan(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:apsara.odps.lot.TableScan)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_apsara_odps_lot_TableScan_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apsara_odps_lot_TableScan_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023lot/tablescan.proto\022\017apsara.odps.lot\032\032" +
      "common/partitionspec.proto\"+\n\tTableScan\022" +
      "\017\n\007Project\030\001 \002(\t\022\r\n\005Table\030\002 \002(\tB\021B\017Table" +
      "ScanProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_apsara_odps_lot_TableScan_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_apsara_odps_lot_TableScan_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_apsara_odps_lot_TableScan_descriptor,
              new String[] { "Project", "Table", },
              TableScan.class,
              TableScan.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PartitionSpecProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
