// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lot/unionall.proto

package apsara.odps.lot;

import apsara.odps.ExpressionProtos;

public final class UnionAllProtos {
  private UnionAllProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UnionAllOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string Id = 1;
    boolean hasId();
    String getId();
    
    // repeated string Parents = 2;
    java.util.List<String> getParentsList();
    int getParentsCount();
    String getParents(int index);
  }
  public static final class UnionAll extends
      com.google.protobuf.GeneratedMessage
      implements UnionAllOrBuilder {
    // Use UnionAll.newBuilder() to construct.
    private UnionAll(Builder builder) {
      super(builder);
    }
    private UnionAll(boolean noInit) {}
    
    private static final UnionAll defaultInstance;
    public static UnionAll getDefaultInstance() {
      return defaultInstance;
    }
    
    public UnionAll getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UnionAllProtos.internal_static_apsara_odps_lot_UnionAll_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UnionAllProtos.internal_static_apsara_odps_lot_UnionAll_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string Id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string Parents = 2;
    public static final int PARENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList parents_;
    public java.util.List<String>
        getParentsList() {
      return parents_;
    }
    public int getParentsCount() {
      return parents_.size();
    }
    public String getParents(int index) {
      return parents_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      for (int i = 0; i < parents_.size(); i++) {
        output.writeBytes(2, parents_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parents_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parents_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParentsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static UnionAll parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static UnionAll parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static UnionAll parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static UnionAll parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static UnionAll parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static UnionAll parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static UnionAll parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static UnionAll parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static UnionAll parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static UnionAll parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UnionAll prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements UnionAllOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UnionAllProtos.internal_static_apsara_odps_lot_UnionAll_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UnionAllProtos.internal_static_apsara_odps_lot_UnionAll_fieldAccessorTable;
      }
      
      // Construct using apsara.odps.lot.UnionAllProtos.UnionAll.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UnionAll.getDescriptor();
      }
      
      public UnionAll getDefaultInstanceForType() {
        return UnionAll.getDefaultInstance();
      }
      
      public UnionAll build() {
        UnionAll result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private UnionAll buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        UnionAll result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public UnionAll buildPartial() {
        UnionAll result = new UnionAll(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          parents_ = new com.google.protobuf.UnmodifiableLazyStringList(
              parents_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.parents_ = parents_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UnionAll) {
          return mergeFrom((UnionAll)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(UnionAll other) {
        if (other == UnionAll.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.parents_.isEmpty()) {
          if (parents_.isEmpty()) {
            parents_ = other.parents_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParentsIsMutable();
            parents_.addAll(other.parents_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              ensureParentsIsMutable();
              parents_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string Id = 1;
      private Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // repeated string Parents = 2;
      private com.google.protobuf.LazyStringList parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParentsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          parents_ = new com.google.protobuf.LazyStringArrayList(parents_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getParentsList() {
        return java.util.Collections.unmodifiableList(parents_);
      }
      public int getParentsCount() {
        return parents_.size();
      }
      public String getParents(int index) {
        return parents_.get(index);
      }
      public Builder setParents(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentsIsMutable();
        parents_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addParents(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentsIsMutable();
        parents_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllParents(
          Iterable<String> values) {
        ensureParentsIsMutable();
        super.addAll(values, parents_);
        onChanged();
        return this;
      }
      public Builder clearParents() {
        parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addParents(com.google.protobuf.ByteString value) {
        ensureParentsIsMutable();
        parents_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:apsara.odps.lot.UnionAll)
    }
    
    static {
      defaultInstance = new UnionAll(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:apsara.odps.lot.UnionAll)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_apsara_odps_lot_UnionAll_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_apsara_odps_lot_UnionAll_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022lot/unionall.proto\022\017apsara.odps.lot\032\027c" +
      "ommon/expression.proto\"\'\n\010UnionAll\022\n\n\002Id" +
      "\030\001 \002(\t\022\017\n\007Parents\030\002 \003(\tB\020B\016UnionAllProto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_apsara_odps_lot_UnionAll_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_apsara_odps_lot_UnionAll_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_apsara_odps_lot_UnionAll_descriptor,
              new String[] { "Id", "Parents", },
              UnionAll.class,
              UnionAll.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ExpressionProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
